### PR TITLE
Option to output extracted messages as js files instead of json

### PR DESCRIPTION
**Pull request by GertjanReynaert**
Adds the option to output extracted messages as Javascript files instead of JSON files.
Adds the option to specify the indentation used in the output files.

### CODE REVIEW

**Comment by ericf** [comment]
Thanks for adding this. I'm curious, how are you using the JS file?

**Comment by GertjanReynaert** [comment]
I don't specifically use these files, but they're less cumbersome for copying
the lines over to the actual file with the translations.

On a personal note, I also do think they look cleaner than their json counterparts.

If you wan't to discourage people to use these files, we might generate this
object to be
```
const messages = {
};
```
instead of
```
export default {
};
```

**Comment by ericf** [comment]
> but they're less cumbersome for copying the lines over to the actual file with the translations.

I'm not sure what you mean by this. Could you explain more?

> On a personal note, I also do think they look cleaner than their json counterparts.

I'm not worried about how _clean_ the files appear, the main thing is to provide data files that can be easily consumed by other tools in peoples' build processes. The primary goal is to have a loss-less data extraction process.

The reason for a JSON file is that it can be consumed by non JavaScript-based tools since all modern languages can consume JSON data. The filesystem structure is retained so more advanced build processes know where the message came from. The reason for an array is to match the order in which the messages are found when parsing the source code. The `description` is data, so therefore it shouldn't be a JavaScript comment which has no semantic value.

Processing the files is [fairly straightforward](https://github.com/yahoo/react-intl/blob/master/examples/translations/scripts/translate.js#L9-L26) and I think is a job that's outside the scope of this plugin.

**Comment by GertjanReynaert** [comment]
Thx for explaining the  thoughts behind the plugin.

At the moment I maintain my translation file by manually adding the missing keys and translations. It would be less cumbersome if I could just copy over the lines from the extracted messages to the translation file, and just replace the default message with the translation.

Previously I was thinking this plugin would grow into a translation management plugin. But it makes total sense to keep this plugins only goal to extract the messages from inside your project. Since the extracted messages then need to be handled by another application / tool / management plugin, it definitely makes sense to extract the messages as JSON.

**Comment by ericf** [comment]
Okay cool. Yeah I want to keep this very targeted since I know each project's build process tends to be unique, this approach requires a bit more work, but should be more flexible for everyone in the end.

**Pull request closed without merging**
