### PR TITLE
Add now option `additionalDescriptorProps`

### PR DESCRIPTION
**Pull request by LoicMahieu**
Allow pick additional properties from the message declaration.

### CODE REVIEW

**Comment by coluccini** [comment]
Love it! It's there a chance to get this merged?

**Comment by longlho** [comment]
What is the use case for this PR? This babel plugin specifically extract out `react-intl`-compatible inputs so having extra props doesn't really fit our use case.

**Review by longlho — CHANGES_REQUESTED** [review]
What is the use case for this PR? This babel plugin specifically extract out react-intl-compatible inputs so having extra props doesn't really fit our use case.

**Comment by LoicMahieu** [comment]
Hi @longlho 
This is a quite old PR ;)

Our primary use-case is to know that a translation is used as html, and so we could make the admin UI aware of that and thus use a rich text editor instead of a simple text input.
But it could be useful for any case where extra information is needed, as exposed in #112 

If you're interested by the change, I'll rebase this branch and resolve the conflict.

**Comment by longlho** [comment]
thanks for the context. Right now this plugin conforms to the `MessageDescriptor` interface which has `id`, `defaultMessage` & `description`. Adding new fields would mean changing the type definition for those which is quite disruptive. I think theoretically you can extra those separately and/or embed those contextual info in `description` as well.

I'm closing this for now :) Thank you for your contribution

**Pull request closed without merging**
