### PR TITLE
Add support for processing `intl.formatMessage` when injection is used.

### PR DESCRIPTION
**Pull request by swernerx**
In our project we had the need to extract from `intl.formatMessage` as well. According to your documentation this is a feature you do not want to include by default. I perfectly understand the reasoning that it is hard, by any system, to automatically check whether it's the `formatMessage` injected by `react-intl`. 

In our case we would prefer using `formatMessage` and life with the risk that some calls might be wrongly analyzed. We just follow the convention that to make it parsable the `formatMessage()` call has to be called in the `intl` object. In our application we feel this limitation is pretty safe - and might be for a lot of other uses. 

I opened this PR for our team to use and for a general discussion on the topic. Probably we can add a parameter to the plugin to enable this non-safe extraction as well.

What do you think?

### CODE REVIEW

**Comment by kasparasg** [comment]
I'd love to see this merged 👍

**Review by SavageWilliam — COMMENTED** [review]
Also need this!

**Comment by atomcorp** [comment]
Thanks @swernerx! This works a treat!

To the maintainers, our app had something like 1,500 formatMessages, the prospect of converting them to use defineMessage was not appealing. As this [person pointed out in 2016 ](https://github.com/yahoo/babel-plugin-react-intl/issues/18#issuecomment-261312919) this should be really obvious in the docs. Although preferably this pull request would be merged!

**Comment by longlho** [comment]
Ack. will review asap

**Comment by macca16** [comment]
I see this was committed in https://github.com/formatjs/formatjs/commit/b57953e8dda7638632f4e40f968acf84954ba5ba by @longlho 

Unfortunately with it being enabled by default it is causing extraction failures in my usage of `this.props.intl.formatMessage()` as I have numerous usages where I defined localisations e.g. 
```
const translations = defineMessages({
    mystring: {
        id: 'keyname',
        description: 'my desc',
        defaultMessage: 'my english',
    },
});
```
and used as follows:
`this.props.intl.formatMessage(translations.mystring)`

Without the suggested option to make this change opt in and no obvious way to opt out of this functionality I needed for now to downgrade `babel-plugin-react-intl` to `3.0.1`

**Comment by longlho** [comment]
@macca16 can u create an issue? THanks!

**Pull request merged**
