### PR TITLE
Adding feature to combine messages into one JSON object file

### PR DESCRIPTION
**Pull request by shadiabuhilal**
__In this PR:__
- Adding feature to combine messages into one JSON object file.
- Upgrade mocha dev dep from 3.0.2 to 5.2.0 ,to fix vulnerabilities.

### CODE REVIEW

**Comment by ifiokjr** [comment]
Any chance this could be merged?

**Comment by longlho** [comment]
If we were to combine into a single file it should preserve `description` for translators as well

**Review by longlho — CHANGES_REQUESTED** [review]
If we were to combine into a single file it should preserve description for translators as well

**Comment by longlho** [comment]
close due to stale

**Pull request closed without merging**
